In [1]:
import numpy as np   
import h5py
import matplotlib.pyplot as plt
from scipy.interpolate import RegularGridInterpolator

In [2]:
f = h5py.File('k.h5', 'r') 
list(f.keys())

['data']

In [3]:
dset = f[u'data']
dset.shape
dset.value.shape

(64, 64, 64)

In [4]:
# list(dset)

In [5]:
dset[0:64,0:64,0:64]
x = np.linspace(-160, 160, 64) 
y = np.linspace(-160, 160, 64)
z = np.linspace(-160, 160, 64)
my_interpolating_function = RegularGridInterpolator((x, y, z), dset.value)
pts = np.array([4.5, 15.3, 18.8]) 
my_interpolating_function(pts)

array([1.45666223e-05])

In [9]:
pts = np.array([[2.1, 6.2, 8.3], [3.3, 5.2, 7.1]])
my_interpolating_function(pts)

array([1.12504124e-05, 1.03547969e-05])

In [11]:
dset.value[0][0][0]

-2.896601605568157e-05

In [13]:
# Apply gradient function
gradx, grady, gradz = np.gradient(dset.value)

In [15]:
gradx.shape

(64, 64, 64)

In [19]:
# To find the gradient at any point
gradx_interpol = RegularGridInterpolator((x, y, z), gradx)
grady_interpol = RegularGridInterpolator((x, y, z), grady)
gradz_interpol = RegularGridInterpolator((x, y, z), gradz)

In [20]:
def get_val_and_grads(pts):
    v, x, y, z = my_interpolating_function(pts), gradx_interpol(
        pts), grady_interpol(pts), gradz_interpol(pts)
    return v, x, y, z

In [21]:
get_val_and_grads(pts)

(array([1.12504124e-05, 1.03547969e-05]),
 array([-2.39047460e-06, -2.22773045e-06]),
 array([-2.27256280e-06, -2.52994627e-06]),
 array([3.58920755e-06, 3.78501885e-06]))